# Generated by Django 5.2.17 on 2026-10-04 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('client_mutation_id', models.CharField(blank=True, max_length=128)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='resources.thematicarea')),
            ],
            options={
                'ordering': ['thematic_area__name', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.program'),
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('client_mutation_id', models.CharField(blank=True, max_length=128)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=32)),
                ('default_resource_type', models.CharField(blank=True, choices=[('livestock', 'Livestock'), ('tool', 'Tool'), ('machinery', 'Machinery'), ('land_plot', 'Land Plot'), ('grant', 'Grant'), ('cash_asset', 'Cash Asset'), ('building_material', 'Building Material'), ('other', 'Other')], max_length=64)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_categories', to='resources.program')),
            ],
            options={
                'ordering': ['program__thematic_area__name', 'program__display_order', 'program__name', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.resourcecategory'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('thematic_area', 'code'), name='unique_program_code_per_thematic_area'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('thematic_area', 'name'), name='unique_program_name_per_thematic_area'),
        ),
        migrations.AddConstraint(
            model_name='resourcecategory',
            constraint=models.UniqueConstraint(fields=('program', 'code'), name='unique_resource_category_code_per_program'),
        ),
        migrations.AddConstraint(
            model_name='resourcecategory',
            constraint=models.UniqueConstraint(fields=('program', 'name'), name='unique_resource_category_name_per_program'),
        ),
    ]
